### create multiple regression with sklearn
### multiple regression example
### import relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

### Load data

In [2]:
data=pd.read_csv(r"C:\Users\A.D AKINWUMI\Desktop\1.02. Multiple linear regression.csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

### create the multiple linear regression
### declear dependent and independent variables x & y

In [4]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

### The Regression

In [5]:
reg = LinearRegression()    # same syntax as simple linear regression
reg.fit(x,y)

LinearRegression()

### To interprete the results

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

### R-squared

In [8]:
reg.score(x,y)

0.4066811952814283

### using adjusted R^2 formula

In [9]:
x.shape   # n=84 (number of observations)
          # p=2 (number of predictors)

(84, 2)

In [10]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### Feature selection

In [11]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [12]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [13]:
p_values.round(3)

array([0.   , 0.676])

### create a summary table

In [14]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [15]:
reg_summary['coeficients'] = reg.coef_
reg_summary['p_values'] = p_values.round(3)
reg_summary

Features  coeficients  p_values
0         SAT     0.001654     0.000
1  Rand 1,2,3    -0.008270     0.676

In [ ]:
# based on the above results we conclude that Rand 1,2,3 does not contribute to our model, so it should be removed